name: lab2

mgmt: 
  network: statics
  ipv4_subnet: 172.40.40.0/24

topology:
  nodes:
    RO1.NY:
      kind: vr-ros
      image: vrnetlab/vr-routeros:6.47.9
      mgmt_ipv4: 172.40.40.40
    RO1.LND:
      kind: vr-ros
      image: vrnetlab/vr-routeros:6.47.9
      mgmt_ipv4: 172.40.40.41
    RO1.LBN:
      kind: vr-ros
      image: vrnetlab/vr-routeros:6.47.9
      mgmt_ipv4: 172.40.40.42
    RO1.HKI:
      kind: vr-ros
      image: vrnetlab/vr-routeros:6.47.9
      mgmt_ipv4: 172.40.40.43
    RO1.MSK:
      kind: vr-ros
      image: vrnetlab/vr-routeros:6.47.9
      mgmt_ipv4: 172.40.40.44
    RO1.SPB:
      kind: vr-ros
      image: vrnetlab/vr-routeros:6.47.9
      mgmt_ipv4: 172.40.40.45 
    SGI_PRISM:
      kind: vr-ros
      image: vrnetlab/vr-routeros:6.47.9
      mgmt_ipv4: 172.40.40.46
    PC1:
      kind: vr-ros
      image: vrnetlab/vr-routeros:6.47.9
      mgmt_ipv4: 172.40.40.47                 
    
  links:
    - endpoints: ["SGI_PRISM:eth1","RO1.NY:eth1"]
    - endpoints: ["RO1.NY:eth2","RO1.LND:eth1"]    
    - endpoints: ["RO1.NY:eth3","RO1.LBN:eth1"]        
    - endpoints: ["RO1.LBN:eth2","RO1.HKI:eth2"] 
    - endpoints: ["RO1.LBN:eth3","RO1.MSK:eth1"]         
    - endpoints: ["RO1.LND:eth2","RO1.HKI:eth1"]     
    - endpoints: ["RO1.HKI:eth3","RO1.SPB:eth1"]     
    - endpoints: ["RO1.SPB:eth2","RO1.MSK:eth2"]      
    - endpoints: ["RO1.SPB:eth3","PC1:eth1"]      
    
    
    
    
    

